// generated by template, do not modify manually

namespace Coplt.Mathematics;

#region float2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2 asfloat(this float2 v) => v.BitCast<float2, float2>();
    [MethodImpl(256 | 512)]
    public static int2 asint(this float2 v) => v.BitCast<float2, int2>();
    [MethodImpl(256 | 512)]
    public static uint2 asuint(this float2 v) => v.BitCast<float2, uint2>();
    [MethodImpl(256 | 512)]
    public static b32v2 asb32(this float2 v) => v.BitCast<float2, b32v2>();
}

#endregion // float2

#region float3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3 asfloat(this float3 v) => v.BitCast<float3, float3>();
    [MethodImpl(256 | 512)]
    public static int3 asint(this float3 v) => v.BitCast<float3, int3>();
    [MethodImpl(256 | 512)]
    public static uint3 asuint(this float3 v) => v.BitCast<float3, uint3>();
    [MethodImpl(256 | 512)]
    public static b32v3 asb32(this float3 v) => v.BitCast<float3, b32v3>();
}

#endregion // float3

#region float4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4 asfloat(this float4 v) => v.BitCast<float4, float4>();
    [MethodImpl(256 | 512)]
    public static int4 asint(this float4 v) => v.BitCast<float4, int4>();
    [MethodImpl(256 | 512)]
    public static uint4 asuint(this float4 v) => v.BitCast<float4, uint4>();
    [MethodImpl(256 | 512)]
    public static b32v4 asb32(this float4 v) => v.BitCast<float4, b32v4>();
}

#endregion // float4

#region double2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2 asdouble(this double2 v) => v.BitCast<double2, double2>();
    [MethodImpl(256 | 512)]
    public static long2 aslong(this double2 v) => v.BitCast<double2, long2>();
    [MethodImpl(256 | 512)]
    public static ulong2 asulong(this double2 v) => v.BitCast<double2, ulong2>();
    [MethodImpl(256 | 512)]
    public static b64v2 asb64(this double2 v) => v.BitCast<double2, b64v2>();
}

#endregion // double2

#region double3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3 asdouble(this double3 v) => v.BitCast<double3, double3>();
    [MethodImpl(256 | 512)]
    public static long3 aslong(this double3 v) => v.BitCast<double3, long3>();
    [MethodImpl(256 | 512)]
    public static ulong3 asulong(this double3 v) => v.BitCast<double3, ulong3>();
    [MethodImpl(256 | 512)]
    public static b64v3 asb64(this double3 v) => v.BitCast<double3, b64v3>();
}

#endregion // double3

#region double4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4 asdouble(this double4 v) => v.BitCast<double4, double4>();
    [MethodImpl(256 | 512)]
    public static long4 aslong(this double4 v) => v.BitCast<double4, long4>();
    [MethodImpl(256 | 512)]
    public static ulong4 asulong(this double4 v) => v.BitCast<double4, ulong4>();
    [MethodImpl(256 | 512)]
    public static b64v4 asb64(this double4 v) => v.BitCast<double4, b64v4>();
}

#endregion // double4

#region short2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2 ashalf(this short2 v) => v.BitCast<short2, half2>();
    [MethodImpl(256 | 512)]
    public static b16v2 asb16(this short2 v) => v.BitCast<short2, b16v2>();
}

#endregion // short2

#region short3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3 ashalf(this short3 v) => v.BitCast<short3, half3>();
    [MethodImpl(256 | 512)]
    public static b16v3 asb16(this short3 v) => v.BitCast<short3, b16v3>();
}

#endregion // short3

#region short4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4 ashalf(this short4 v) => v.BitCast<short4, half4>();
    [MethodImpl(256 | 512)]
    public static b16v4 asb16(this short4 v) => v.BitCast<short4, b16v4>();
}

#endregion // short4

#region ushort2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2 ashalf(this ushort2 v) => v.BitCast<ushort2, half2>();
    [MethodImpl(256 | 512)]
    public static b16v2 asb16(this ushort2 v) => v.BitCast<ushort2, b16v2>();
}

#endregion // ushort2

#region ushort3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3 ashalf(this ushort3 v) => v.BitCast<ushort3, half3>();
    [MethodImpl(256 | 512)]
    public static b16v3 asb16(this ushort3 v) => v.BitCast<ushort3, b16v3>();
}

#endregion // ushort3

#region ushort4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4 ashalf(this ushort4 v) => v.BitCast<ushort4, half4>();
    [MethodImpl(256 | 512)]
    public static b16v4 asb16(this ushort4 v) => v.BitCast<ushort4, b16v4>();
}

#endregion // ushort4

#region int2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2 asfloat(this int2 v) => v.BitCast<int2, float2>();
    [MethodImpl(256 | 512)]
    public static int2 asint(this int2 v) => v.BitCast<int2, int2>();
    [MethodImpl(256 | 512)]
    public static uint2 asuint(this int2 v) => v.BitCast<int2, uint2>();
    [MethodImpl(256 | 512)]
    public static b32v2 asb32(this int2 v) => v.BitCast<int2, b32v2>();
}

#endregion // int2

#region int3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3 asfloat(this int3 v) => v.BitCast<int3, float3>();
    [MethodImpl(256 | 512)]
    public static int3 asint(this int3 v) => v.BitCast<int3, int3>();
    [MethodImpl(256 | 512)]
    public static uint3 asuint(this int3 v) => v.BitCast<int3, uint3>();
    [MethodImpl(256 | 512)]
    public static b32v3 asb32(this int3 v) => v.BitCast<int3, b32v3>();
}

#endregion // int3

#region int4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4 asfloat(this int4 v) => v.BitCast<int4, float4>();
    [MethodImpl(256 | 512)]
    public static int4 asint(this int4 v) => v.BitCast<int4, int4>();
    [MethodImpl(256 | 512)]
    public static uint4 asuint(this int4 v) => v.BitCast<int4, uint4>();
    [MethodImpl(256 | 512)]
    public static b32v4 asb32(this int4 v) => v.BitCast<int4, b32v4>();
}

#endregion // int4

#region uint2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2 asfloat(this uint2 v) => v.BitCast<uint2, float2>();
    [MethodImpl(256 | 512)]
    public static int2 asint(this uint2 v) => v.BitCast<uint2, int2>();
    [MethodImpl(256 | 512)]
    public static uint2 asuint(this uint2 v) => v.BitCast<uint2, uint2>();
    [MethodImpl(256 | 512)]
    public static b32v2 asb32(this uint2 v) => v.BitCast<uint2, b32v2>();
}

#endregion // uint2

#region uint3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3 asfloat(this uint3 v) => v.BitCast<uint3, float3>();
    [MethodImpl(256 | 512)]
    public static int3 asint(this uint3 v) => v.BitCast<uint3, int3>();
    [MethodImpl(256 | 512)]
    public static uint3 asuint(this uint3 v) => v.BitCast<uint3, uint3>();
    [MethodImpl(256 | 512)]
    public static b32v3 asb32(this uint3 v) => v.BitCast<uint3, b32v3>();
}

#endregion // uint3

#region uint4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4 asfloat(this uint4 v) => v.BitCast<uint4, float4>();
    [MethodImpl(256 | 512)]
    public static int4 asint(this uint4 v) => v.BitCast<uint4, int4>();
    [MethodImpl(256 | 512)]
    public static uint4 asuint(this uint4 v) => v.BitCast<uint4, uint4>();
    [MethodImpl(256 | 512)]
    public static b32v4 asb32(this uint4 v) => v.BitCast<uint4, b32v4>();
}

#endregion // uint4

#region long2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2 asdouble(this long2 v) => v.BitCast<long2, double2>();
    [MethodImpl(256 | 512)]
    public static long2 aslong(this long2 v) => v.BitCast<long2, long2>();
    [MethodImpl(256 | 512)]
    public static ulong2 asulong(this long2 v) => v.BitCast<long2, ulong2>();
    [MethodImpl(256 | 512)]
    public static b64v2 asb64(this long2 v) => v.BitCast<long2, b64v2>();
}

#endregion // long2

#region long3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3 asdouble(this long3 v) => v.BitCast<long3, double3>();
    [MethodImpl(256 | 512)]
    public static long3 aslong(this long3 v) => v.BitCast<long3, long3>();
    [MethodImpl(256 | 512)]
    public static ulong3 asulong(this long3 v) => v.BitCast<long3, ulong3>();
    [MethodImpl(256 | 512)]
    public static b64v3 asb64(this long3 v) => v.BitCast<long3, b64v3>();
}

#endregion // long3

#region long4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4 asdouble(this long4 v) => v.BitCast<long4, double4>();
    [MethodImpl(256 | 512)]
    public static long4 aslong(this long4 v) => v.BitCast<long4, long4>();
    [MethodImpl(256 | 512)]
    public static ulong4 asulong(this long4 v) => v.BitCast<long4, ulong4>();
    [MethodImpl(256 | 512)]
    public static b64v4 asb64(this long4 v) => v.BitCast<long4, b64v4>();
}

#endregion // long4

#region ulong2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2 asdouble(this ulong2 v) => v.BitCast<ulong2, double2>();
    [MethodImpl(256 | 512)]
    public static long2 aslong(this ulong2 v) => v.BitCast<ulong2, long2>();
    [MethodImpl(256 | 512)]
    public static ulong2 asulong(this ulong2 v) => v.BitCast<ulong2, ulong2>();
    [MethodImpl(256 | 512)]
    public static b64v2 asb64(this ulong2 v) => v.BitCast<ulong2, b64v2>();
}

#endregion // ulong2

#region ulong3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3 asdouble(this ulong3 v) => v.BitCast<ulong3, double3>();
    [MethodImpl(256 | 512)]
    public static long3 aslong(this ulong3 v) => v.BitCast<ulong3, long3>();
    [MethodImpl(256 | 512)]
    public static ulong3 asulong(this ulong3 v) => v.BitCast<ulong3, ulong3>();
    [MethodImpl(256 | 512)]
    public static b64v3 asb64(this ulong3 v) => v.BitCast<ulong3, b64v3>();
}

#endregion // ulong3

#region ulong4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4 asdouble(this ulong4 v) => v.BitCast<ulong4, double4>();
    [MethodImpl(256 | 512)]
    public static long4 aslong(this ulong4 v) => v.BitCast<ulong4, long4>();
    [MethodImpl(256 | 512)]
    public static ulong4 asulong(this ulong4 v) => v.BitCast<ulong4, ulong4>();
    [MethodImpl(256 | 512)]
    public static b64v4 asb64(this ulong4 v) => v.BitCast<ulong4, b64v4>();
}

#endregion // ulong4

#region decimal2

public static partial class math
{
}

#endregion // decimal2

#region decimal3

public static partial class math
{
}

#endregion // decimal3

#region decimal4

public static partial class math
{
}

#endregion // decimal4

#region half2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2 ashalf(this half2 v) => v.BitCast<half2, half2>();
    [MethodImpl(256 | 512)]
    public static b16v2 asb16(this half2 v) => v.BitCast<half2, b16v2>();
}

#endregion // half2

#region half3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3 ashalf(this half3 v) => v.BitCast<half3, half3>();
    [MethodImpl(256 | 512)]
    public static b16v3 asb16(this half3 v) => v.BitCast<half3, b16v3>();
}

#endregion // half3

#region half4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4 ashalf(this half4 v) => v.BitCast<half4, half4>();
    [MethodImpl(256 | 512)]
    public static b16v4 asb16(this half4 v) => v.BitCast<half4, b16v4>();
}

#endregion // half4

#region b16v2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half2 ashalf(this b16v2 v) => v.BitCast<b16v2, half2>();
    [MethodImpl(256 | 512)]
    public static b16v2 asb16(this b16v2 v) => v.BitCast<b16v2, b16v2>();
}

#endregion // b16v2

#region b16v3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half3 ashalf(this b16v3 v) => v.BitCast<b16v3, half3>();
    [MethodImpl(256 | 512)]
    public static b16v3 asb16(this b16v3 v) => v.BitCast<b16v3, b16v3>();
}

#endregion // b16v3

#region b16v4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static half4 ashalf(this b16v4 v) => v.BitCast<b16v4, half4>();
    [MethodImpl(256 | 512)]
    public static b16v4 asb16(this b16v4 v) => v.BitCast<b16v4, b16v4>();
}

#endregion // b16v4

#region b32v2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float2 asfloat(this b32v2 v) => v.BitCast<b32v2, float2>();
    [MethodImpl(256 | 512)]
    public static int2 asint(this b32v2 v) => v.BitCast<b32v2, int2>();
    [MethodImpl(256 | 512)]
    public static uint2 asuint(this b32v2 v) => v.BitCast<b32v2, uint2>();
    [MethodImpl(256 | 512)]
    public static b32v2 asb32(this b32v2 v) => v.BitCast<b32v2, b32v2>();
}

#endregion // b32v2

#region b32v3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float3 asfloat(this b32v3 v) => v.BitCast<b32v3, float3>();
    [MethodImpl(256 | 512)]
    public static int3 asint(this b32v3 v) => v.BitCast<b32v3, int3>();
    [MethodImpl(256 | 512)]
    public static uint3 asuint(this b32v3 v) => v.BitCast<b32v3, uint3>();
    [MethodImpl(256 | 512)]
    public static b32v3 asb32(this b32v3 v) => v.BitCast<b32v3, b32v3>();
}

#endregion // b32v3

#region b32v4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static float4 asfloat(this b32v4 v) => v.BitCast<b32v4, float4>();
    [MethodImpl(256 | 512)]
    public static int4 asint(this b32v4 v) => v.BitCast<b32v4, int4>();
    [MethodImpl(256 | 512)]
    public static uint4 asuint(this b32v4 v) => v.BitCast<b32v4, uint4>();
    [MethodImpl(256 | 512)]
    public static b32v4 asb32(this b32v4 v) => v.BitCast<b32v4, b32v4>();
}

#endregion // b32v4

#region b64v2

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double2 asdouble(this b64v2 v) => v.BitCast<b64v2, double2>();
    [MethodImpl(256 | 512)]
    public static long2 aslong(this b64v2 v) => v.BitCast<b64v2, long2>();
    [MethodImpl(256 | 512)]
    public static ulong2 asulong(this b64v2 v) => v.BitCast<b64v2, ulong2>();
    [MethodImpl(256 | 512)]
    public static b64v2 asb64(this b64v2 v) => v.BitCast<b64v2, b64v2>();
}

#endregion // b64v2

#region b64v3

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double3 asdouble(this b64v3 v) => v.BitCast<b64v3, double3>();
    [MethodImpl(256 | 512)]
    public static long3 aslong(this b64v3 v) => v.BitCast<b64v3, long3>();
    [MethodImpl(256 | 512)]
    public static ulong3 asulong(this b64v3 v) => v.BitCast<b64v3, ulong3>();
    [MethodImpl(256 | 512)]
    public static b64v3 asb64(this b64v3 v) => v.BitCast<b64v3, b64v3>();
}

#endregion // b64v3

#region b64v4

public static partial class math
{
    [MethodImpl(256 | 512)]
    public static double4 asdouble(this b64v4 v) => v.BitCast<b64v4, double4>();
    [MethodImpl(256 | 512)]
    public static long4 aslong(this b64v4 v) => v.BitCast<b64v4, long4>();
    [MethodImpl(256 | 512)]
    public static ulong4 asulong(this b64v4 v) => v.BitCast<b64v4, ulong4>();
    [MethodImpl(256 | 512)]
    public static b64v4 asb64(this b64v4 v) => v.BitCast<b64v4, b64v4>();
}

#endregion // b64v4
